version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - app-network
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    networks:
      - app-network

  booking-service:
    build: ./booking-service
    ports:
      - "3003:3003"
    env_file:
      - ./booking-service/.env
    networks:
      - app-network

  event-service:
    build: ./event-service
    ports:
      - "3002:3002"
    env_file:
      - ./event-service/.env
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    env_file:
      - ./notification-service/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
